name: Latest issue contributor
on:
  issues:
    types: [closed]
jobs:
  check_latest_contributor:
    runs-on: ubuntu-latest
    steps:
    - name: Update GitHub Profile README
      uses: theboi/github-update-readme@v1.3.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        header: "Latest issue closed by: ${{ github.actor }}."
        repoCount: 0
